### ISSUE TITLE
Topologic PY installation returns cppyy output error about libTopologic.so

### ISSUE THREAD

**Issue by nortikin** [NonManifoldTopology/Topologic#20]
## Debian 10 4.19.171-2 x86-64 GNU/linux 4.19.0-14-amd64

* Installed as in https://github.com/wassimj/topologicPy except debian apt has `libfreetype6-dev` instead of `libfreetype-dev`
* Operating System and version (desktop or mobile): desktop

## Context
All steps ok, but when checking:

## Expected Behavior
`python3 import topologic`
no error

## Current Behavior
`python3 import topologic`
```bash
Traceback (most recent call last):
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/ololo/.config/blender/2.90/scripts/addons/topologicsverchok/__init__.py", line 31, in <module>
    from topologic import Vertex, Edge, Wire, Face, Shell, Cell, CellComplex, Cluster
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/python/lib/python3.7/site-packages/topologic/__init__.py", line 101, in <module>
    cppyy.include(topologic_inc + "/" + header )
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/python/lib/python3.7/site-packages/cppyy/__init__.py", line 229, in include
    raise ImportError('Failed to load header file "%s"%s' % (header, err.err))
ImportError: Failed to load header file "/usr/local/include/TopologicCore/Aperture.h"
In file included from input_line_19:1:
In file included from /usr/local/include/TopologicCore/Aperture.h:20:
In file included from /usr/local/include/TopologicCore/Topology.h:22:
/usr/local/include/TopologicCore/Dictionary.h:40:9: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
        auto GetEnumerator() { return this->begin(); }
        ^
/usr/local/include/TopologicCore/Dictionary.h:40:39: error: no viable conversion from returned value of type 'std::map<std::basic_string<char>, std::shared_ptr<TopologicCore::Attribute>,
      std::less<std::basic_string<char> >, std::allocator<std::pair<const std::basic_string<char>, std::shared_ptr<TopologicCore::Attribute> > > >::iterator' (aka '_Rb_tree_iterator<std::pair<const std::basic_string<char>,
      std::shared_ptr<TopologicCore::Attribute> > >') to function return type 'int'
        auto GetEnumerator() { return this->begin(); }
                                      ^~~~~~~~~~~~~
```

**Comment by nortikin** [comment]
it is ok. it was owner problem
chown -R %me%:%me% solved this for cppyy and topologic both
